### ISSUE TITLE
Traefik needs to allow CSP and CORS for owgw-ui

### ISSUE THREAD

**Issue by bsodmike** [Telecominfraproject/wlan-cloud-ucentral-deploy#85]
Hi,

I'm seeing many CSP and CORS errors when attempting to access owgw-ui on port 443.  I've even tried adding middleware to allow CORS and CSP as follows - however, this doesn't work.  I get CSP errors on `/favicon.ico`, all access to `/js` and frequently `{"ErrorCode":400,"ErrorDescription":"1004: Unsupported HTTP Method","ErrorDetails":"GET"}`.

```
http:
  middlewares:
    cors:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
          - POST
          - PATCH
        accessControlAllowOriginList:
          - https://openwifi.internal.example.network
          - https://openwifi-local.internal.example.network
    csp:
      headers:
          contentSecurityPolicy: "default-src * 'unsafe-inline' 'unsafe-eval'; script-src * 'unsafe-inline' 'unsafe-eval'; connect-src * 'unsafe-inline'; img-src * data: blob: 'unsafe-inline'; frame-src *; style-src * 'unsafe-inline';"
```

Thoughts?
